### ISSUE TITLE
clearer error in the case of a nonexistent bucket

### ISSUE THREAD

**Issue by mathjeff** [googleapis/java-storage#1372]
Currently when I (accidentally) attempt to read from a nonexistent bucket, I get an error that says `  com.google.cloud.storage.StorageException: [rolename] does not have storage.objects.get access to the Google Cloud Storage object.` :

This caused me to investigate whether the permissions and roles were set up correctly. I later discovered that the actual error was that the bucket name I was trying to connect to didn't match the actual name of the bucket.

It could be helpful if the error message could do something like:
A) suggest that maybe the bucket doesn't exist: "this Storage object does not exist or [rolename] does not have access to it"
B) mention the name of the storage object: "[rolename] does not have storage.objects.get access to [bucket]"

The full stacktrace I was observing:

```
  > Task :buildSrc:jetpad-integration:compileJava
  Could not load entry 48e7b1c0ea46c608a2dcbb6aa66128ad from remote build cache
  com.google.cloud.storage.StorageException: [role name] does not have storage.objects.get access to the Google Cloud Storage object.
  	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:233)
  	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:458)
  	at com.google.cloud.storage.StorageImpl.lambda$get$6(StorageImpl.java:281)
  	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
  	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
  	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
  	at com.google.cloud.storage.Retrying.run(Retrying.java:51)
  	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1376)
  	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:280)
  	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:286)
  	at androidx.build.gradle.gcpbuildcache.GcpStorageService$Companion.load(GcpStorageService.kt:111)
  	at androidx.build.gradle.gcpbuildcache.GcpStorageService$Companion.access$load(GcpStorageService.kt:91)
  	at androidx.build.gradle.gcpbuildcache.GcpStorageService.load(GcpStorageService.kt:54)
  	at androidx.build.gradle.gcpbuildcache.GcpBuildCacheService.load(GcpBuildCacheService.kt:58)
  Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  GET https://storage.googleapis.com/storage/v1/b/[bucket]/o/48e7b1c0ea46c608a2dcbb6aa66128ad?projection=full
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "global",
      "message" : "[rolename] does not have storage.objects.get access to the Google Cloud Storage object.",
      "reason" : "forbidden"
    } ],
    "message" : "[rolename] does not have storage.objects.get access to the Google Cloud Storage object."
  }
  	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
  	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
  	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
  	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
  	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
  	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
  	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
  	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
  	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:455)
```

Thanks

**Comment by JesseLovelace** [comment]
Hi,

Sorry for the late response on this, but can you show what code causes this behavior for you? Because I'm not able to reproduce it. If I run

```
Bucket bucket = storage.get("somenonexistentbucket");
System.out.println(b);
```

The result for me is that `bucket` is null, no error about permissions

**Comment by mathjeff** [comment]
Based on the stacktrace it appears that we were using this at https://github.com/androidx/gcp-gradle-build-cache/blob/7c18de78b8f48ca39a9172c84a681129956d1eed/gcpbuildcache/src/main/kotlin/androidx/build/gradle/gcpbuildcache/GcpStorageService.kt#L111 when trying to read a blob.

It appears that we added our own check for this at https://github.com/androidx/gcp-gradle-build-cache/pull/24/commits/f4d34dfe180c9d8438b12d73ba9cadd36d4a832c

I don't seem to be able to reproduce this anymore and when I try to access the bucket via `curl` the error seems to be more helpful now:

```
$ curl https://storage.googleapis.com/storage/v1/b/bucketmisspelled/o/48e7b1c0ea46c608a2dcbb6aa66128ad?projection=full
{
  "error": {
    "code": 404,
    "message": "The specified bucket does not exist.",
    "errors": [
      {
        "message": "The specified bucket does not exist.",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
```
