### ISSUE TITLE
Add StorageException "Error writing request body to server" to DefaultStorageRetryStrategy

### ISSUE THREAD

**Issue by tomasherman** [googleapis/java-storage#1445]
Hello,

Im using `StorageRetryStrategy.getUniformStorageRetryStrategy()` and i observe the following error: 

```
com.google.cloud.storage.StorageException: Error writing request body to server
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:233)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse(HttpStorageRpc.java:901)
    at com.google.cloud.storage.BlobWriteChannel.transmitChunk(BlobWriteChannel.java:67)
    at com.google.cloud.storage.BlobWriteChannel.access$1400(BlobWriteChannel.java:34)
    at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:252)
```

I believe this kind of error should be retried by default and therefore should be covered by `DefaultStorageRetryStrategy`. Do you agree? Would it be possible to add it? From the code it doesn't seem like a trivial change but maybe you have some tricks :)

**Comment by BenWhitehead** [comment]
Hi @tomasherman,

Do you have a more full exception with the cause or the json error?

We prefer to shy away from matching on exception messages due the inherent fragility. We've had multiple instances in the past where error messages get fixed/improved by the backend and causes bugs.

If we've got a "reason" we can more reliable match on, or an underlying exception from java it's more possible to try and specifically handle this.

**Comment by tomasherman** [comment]
This is the best i can do:

```
com.google.cloud.storage.StorageException: Error writing request body to server

at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate ( com/google.cloud.storage.spi.v1/HttpStorageRpc.java:233 )
at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse ( com/google.cloud.storage.spi.v1/HttpStorageRpc.java:901 )
at com.google.cloud.storage.BlobWriteChannel.transmitChunk ( com/google.cloud.storage/BlobWriteChannel.java:67 )
at com.google.cloud.storage.BlobWriteChannel.access$1400 ( com/google.cloud.storage/BlobWriteChannel.java:34 )
at com.google.cloud.storage.BlobWriteChannel$1.run ( com/google.cloud.storage/BlobWriteChannel.java:252 )
at java.util.concurrent.Executors$RunnableAdapter.call ( java/util.concurrent/Executors.java:539 )
at com.google.api.gax.retrying.DirectRetryingExecutor.submit ( com/google.api.gax.retrying/DirectRetryingExecutor.java:103 )
at com.google.cloud.RetryHelper.run ( com/google.cloud/RetryHelper.java:76 )
at com.google.cloud.RetryHelper.runWithRetries ( com/google.cloud/RetryHelper.java:50 )
at com.google.cloud.storage.BlobWriteChannel.flushBuffer ( com/google.cloud.storage/BlobWriteChannel.java:183 )
at com.google.cloud.BaseWriteChannel.flush ( com/google.cloud/BaseWriteChannel.java:112 )
at com.google.cloud.BaseWriteChannel.write ( com/google.cloud/BaseWriteChannel.java:139 )
at com.google.common.io.ByteStreams.copy ( com/google.common.io/ByteStreams.java:155 )
at com.avast.analytics.hdfsdumper.writer.GCSFilePublisher.publishFile ( [com/avast.analytics.hdfsdumper.writer/GCSFilePublisher.java:52](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.writer%2FGCSFilePublisher.java&line=52&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.writer.AbstractWriter.moveFileFromTempToDestination ( [com/avast.analytics.hdfsdumper.writer/AbstractWriter.java:43](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.writer%2FAbstractWriter.java&line=43&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.writer.ParquetFileWriter.close ( [com/avast.analytics.hdfsdumper.writer/ParquetFileWriter.java:48](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.writer%2FParquetFileWriter.java&line=48&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.consumer.HdfsConsumer.closeAllFilesAndCommitOffsetSafely ( [com/avast.analytics.hdfsdumper.consumer/HdfsConsumer.java:633](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FHdfsConsumer.java&line=633&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.consumer.HdfsConsumer.closeAllOpenedFiles ( [com/avast.analytics.hdfsdumper.consumer/HdfsConsumer.java:783](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FHdfsConsumer.java&line=783&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.consumer.PerPartitionConsumer.lambda$optionallyCloseAllOpenedFilesPeriodically$5 ( [com/avast.analytics.hdfsdumper.consumer/PerPartitionConsumer.java:301](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FPerPartitionConsumer.java&line=301&project=ppp-bds-data-lake-56) )
at java.util.HashMap.forEach ( java/util/HashMap.java:1421 )
at com.avast.analytics.hdfsdumper.consumer.PerPartitionConsumer.optionallyCloseAllOpenedFilesPeriodically ( [com/avast.analytics.hdfsdumper.consumer/PerPartitionConsumer.java:301](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FPerPartitionConsumer.java&line=301&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.consumer.PerPartitionConsumer.periodicTasks ( [com/avast.analytics.hdfsdumper.consumer/PerPartitionConsumer.java:250](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FPerPartitionConsumer.java&line=250&project=ppp-bds-data-lake-56) )
at com.avast.analytics.hdfsdumper.consumer.PerPartitionConsumer.processMessages ( [com/avast.analytics.hdfsdumper.consumer/PerPartitionConsumer.java:212](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.analytics.hdfsdumper.consumer%2FPerPartitionConsumer.java&line=212&project=ppp-bds-data-lake-56) )
at com.avast.utils2.kafka.consumer.ConsumerThread.pollAndProcessMessagesFromKafka ( [com/avast.utils2.kafka.consumer/ConsumerThread.java:239](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.utils2.kafka.consumer%2FConsumerThread.java&line=239&project=ppp-bds-data-lake-56) )
at com.avast.utils2.kafka.consumer.ConsumerThread.run ( [com/avast.utils2.kafka.consumer/ConsumerThread.java:172](https://console.cloud.google.com/debug?referrer=fromlog&file=com%2Favast.utils2.kafka.consumer%2FConsumerThread.java&line=172&project=ppp-bds-data-lake-56) )
at java.util.concurrent.Executors$RunnableAdapter.call ( java/util.concurrent/Executors.java:539 )
at java.util.concurrent.FutureTask.run ( java/util.concurrent/FutureTask.java:264 )
at java.util.concurrent.ThreadPoolExecutor.runWorker ( java/util.concurrent/ThreadPoolExecutor.java:1136 )
at java.util.concurrent.ThreadPoolExecutor$Worker.run ( java/util.concurrent/ThreadPoolExecutor.java:635 )
at java.lang.Thread.run ( java/lang/Thread.java:833 )
```

Not wanting to match on exception messages makes total sense to me, but unfortunately i don't think there is anything better at to match on at this point :(

**Comment by frankyn** [comment]
Hi @BenWhitehead,

The error may be coming from an IOException and in java-core we have a case to retry this error based on the error message (it might not have an alternative). 

https://github.com/googleapis/java-core/blob/main/google-cloud-core/src/main/java/com/google/cloud/BaseServiceException.java#L256-L266

IIUC, java-storage doesn't consider idempotency from BaseServiceException which could tell the client that it's retriable.

**Comment by frankyn** [comment]
@danielduhh called out that we do retry this right now in https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java#L84

Which version are you on @tomasherman?

**Comment by BenWhitehead** [comment]
One other reference item, we do in fact have a test[1] to ensure retry of this error message when a request is idempotent.

When you are creating your `WriteChannel` are you setting a precondition on it so the request is idempotent?

[1] https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java#L457-L466

**Comment by BenWhitehead** [comment]
Closing this out as I believe it's covered already.
