### ISSUE TITLE
com.google.cloud.storage.Storage#copy fails with "412 Precondition Failed" *after* retry

### ISSUE THREAD

**Issue by ewirch** [googleapis/java-storage#1453]
Using com.google.cloud:google-cloud-storage:2.3.0.

I know no way to reproduce the problem. It happens occasionally in production. I assume under the influence of network issues. 

We use a generation-match precondition, to make the operation retry-able. Sometimes, when copying a file to a new (non existing) file name, the operation fails with "412 Precondition Failed". But the file was actually copied. I see all the file contents under the target file name. This is why I suspect, that it fails when retrying the copy operation.

```java
com.google.cloud.storage.Storage storage;

void copyTo(Blob source, Path newFullPath) {
    var copyRequest = createCopyRequest(source, newFullPath);
    var copyWriter = storage.copy(copyRequest);
    while (!copyWriter.isDone()) {
        copyWriter.copyChunk();
    }
}

Storage.CopyRequest createCopyRequest(Blob source, Path newFullPath) {
    return Storage.CopyRequest.newBuilder()
        .setSource(source.getBlobId())
        // In order to get advantage of the automatic GCS operation re-tries, target file needs to have generation check enabled.
        .setTarget(BlobId.of(bucketInfo.getName(), newFullPath.toString(), 0L), Storage.BlobTargetOption.generationMatch())
        .build();
}

```

Failure stack trace:
```
com.google.cloud.storage.StorageException: At least one of the pre-conditions you specified did not hold.
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:233)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.rewrite(HttpStorageRpc.java:1065)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.openRewrite(HttpStorageRpc.java:995)
	at com.google.cloud.storage.StorageImpl.lambda$copy$22(StorageImpl.java:509)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.Retrying.run(Retrying.java:51)
	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1374)
	at com.google.cloud.storage.StorageImpl.copy(StorageImpl.java:507)
	< ... our frames ... >
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 412 Precondition Failed
POST https://storage.googleapis.com/storage/v1/b/our-bucket/o/upload-20220614-091249-0000.xml.unverified/rewriteTo/b/our-bucket/o/upload-20220614-091249-0000.xml?ifGenerationMatch=0&projection=full&sourceGeneration=1655197969531487
{
  "code" : 412,
  "errors" : [ {
    "domain" : "global",
    "location" : "If-Match",
    "locationType" : "header",
    "message" : "At least one of the pre-conditions you specified did not hold.",
    "reason" : "conditionNotMet"
  } ],
  "message" : "At least one of the pre-conditions you specified did not hold."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.rewrite(HttpStorageRpc.java:1055)
	... 135 common frames omitted

```

**Comment by frankyn** [comment]
Hi @ewirch,

Looks like a a prior request succeeded but the result did not make it to the client so it retried.

If you're only using preconditions to enable retries; I'd recommend using UniformStorageRetryStrategy to always retry.

```
StorageOptions alwaysRetryStorageOptions =
        StorageOptions.newBuilder()
            // Customize retry so all requests are retried even if they are non-idempotent.
            .setStorageRetryStrategy(StorageRetryStrategy.getUniformStorageRetryStrategy())
            // provide the previously configured retrySettings
            .setRetrySettings(retrySettings)
            .build();

    // Instantiate a client
    Storage storage = alwaysRetryStorageOptions.getService();
```

Alternatively, you can catch the StorageException and confirm that it is a `HTTP 412` and ignore it if the state of the file is correct.

Let me know what you think, cheers

**Comment by frankyn** [comment]
Hi @ewirch, agreed, the API team is aware of the issue and working to make all requests idempotent so the last known result is returned instead of a 412 for example. 

Apologies for the friction in this case.

**Comment by frankyn** [comment]
Closing issue as this is a question until the API changes.
