### ISSUE TITLE
Storage: Could not initialize class com.google.common.io.BaseEncoding 

### ISSUE THREAD

**Issue by asm0dey** [googleapis/java-storage#174]
With following envronment:

```
JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
OS: Windows 10 
```

I'm getting following error:

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.common.io.BaseEncoding
	at com.google.api.client.util.Base64.decodeBase64(Base64.java:101)
	at com.google.api.client.util.PemReader.readNextSection(PemReader.java:99)
	at com.google.api.client.util.PemReader.readFirstSectionAndClose(PemReader.java:128)
	at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8(ServiceAccountCredentials.java:333)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8(ServiceAccountCredentials.java:316)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromJson(ServiceAccountCredentials.java:189)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:166)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:133)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver$connectionOptions$2.invoke(GCSDriver.kt:53)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver$connectionOptions$2.invoke(GCSDriver.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver.getConnectionOptions(GCSDriver.kt)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver.<init>(GCSDriver.kt:57)
	at org.jetbrains.hdfsplugin.hdfs.drivers.DriverCreator.createGCSDriver(DriverCreator.kt:82)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData.createDriver(GCSConnectionSettingsProvider.kt:49)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData$createConfigurable$1$createConnectionTesting$1.invoke(GCSConnectionSettingsProvider.kt:45)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData$createConfigurable$1$createConnectionTesting$1.invoke(GCSConnectionSettingsProvider.kt:40)
	at org.jetbrains.hdfsplugin.hdfs.settings.HdfsConnectionTesting.testConnection(HdfsConnectionSettingsProvider.kt:273)
	at com.jetbrains.bigdatatools.settings.defaultui.TestConnectionPanelWrapper$runTesting$1.run(TestConnectionPanelWrapper.kt:63)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

We can't reproduce this error on other OSes.

As you can see it happens in internals of driver while trying to decode base64.

Any ideas on reasons and possible fixes?

**Comment by athakor** [comment]
@asm0dey This sounds likely to be some problem with your build system setup. Can you provide some more details

**Comment by asm0dey** [comment]
@athakor that's not that easy. I'm developing plugin for IntelliJ IDEA, which is able to browse GCS. We're not using any traditional build system — it's being built as part of IDEA with help of IDEA model. But we can see this as some sort of Ant build.
What looks strange for me: it works with MacOS and Linux, how is it possible that it doesn't work with Windows?

Please tell me which detail I can provide you with and I'll do it.
I definitely can share built version of plugin with you if you wish, bot not sure about source code.

**Comment by dmitry-fa** [comment]
@asm0dey 
> JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 

Can you check please if the problem exists if Oracle JDK is used.

**Comment by asm0dey** [comment]
@dmitry-fa but it's not free :(

**Comment by dmitry-fa** [comment]
I think it's free:
https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html

> Is Java still free?
Yes. For over a decade, Oracle stewards the OpenJDK open source community and provides the latest stability, performance and security updates to the latest release.

**Comment by asm0dey** [comment]
Well, of course it's free, but only for a developer IIRC. Is it still free for enterprise usage?

Also I can see here words about OpenJDK, but not OacleJDK. And if we're speaking about OpenJDK — there are lots of distributions. JBR is just one of them.

**Comment by dmitry-fa** [comment]
Yes, Oracle suggests the same binaries under various licenses including commercial (Java SE subscription) Your case is:
> “Development Use” refers to Your internal use of the Programs to develop, test, prototype and demonstrate Your Applications. For purposes of clarity, the “to develop” grant includes using the Programs to run profilers, debuggers and Integrated Development Environments (IDE Tools) where the primary purpose of the IDE Tools is profiling, debugging and source code editing Applications. 

If you afraid of using oracle jdk, could you try any alternative Java SDK or JBR JDK 8.

**Comment by asm0dey** [comment]
I will, thank you

**Comment by asm0dey** [comment]
Surprisingly, I've got another stacktrace under vanilla OpenJDK

```
2020-03-16 09:38:09,496 [  81671]  ERROR - plication.impl.ApplicationImpl - com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V 
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V
	at com.google.common.io.BaseEncoding$Alphabet.<init>(BaseEncoding.java:458)
	at com.google.common.io.BaseEncoding$Base64Encoding.<init>(BaseEncoding.java:940)
	at com.google.common.io.BaseEncoding.<clinit>(BaseEncoding.java:322)
	at com.google.api.client.util.Base64.decodeBase64(Base64.java:101)
	at com.google.api.client.util.PemReader.readNextSection(PemReader.java:97)
	at com.google.api.client.util.PemReader.readFirstSectionAndClose(PemReader.java:126)
	at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8(ServiceAccountCredentials.java:333)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8(ServiceAccountCredentials.java:316)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromJson(ServiceAccountCredentials.java:189)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:166)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:133)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver$connectionOptions$2.invoke(GCSDriver.kt:32)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver$connectionOptions$2.invoke(GCSDriver.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver.getConnectionOptions(GCSDriver.kt)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver.<init>(GCSDriver.kt:36)
	at org.jetbrains.hdfsplugin.hdfs.drivers.DriverCreator.createGCSDriver(DriverCreator.kt:86)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData.createDriver(GCSConnectionSettingsProvider.kt:56)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData$createConfigurable$1$createConnectionTesting$1.invoke(GCSConnectionSettingsProvider.kt:51)
	at org.jetbrains.hdfsplugin.hdfs.settings.GCSConnectionData$createConfigurable$1$createConnectionTesting$1.invoke(GCSConnectionSettingsProvider.kt:41)
	at org.jetbrains.hdfsplugin.hdfs.settings.HdfsConnectionTesting.testConnection(HdfsConnectionSettingsProvider.kt:278)
	at com.jetbrains.bigdatatools.settings.defaultui.TestConnectionPanelWrapper$runTesting$1.run(TestConnectionPanelWrapper.kt:63)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-16 09:38:09,514 [  81689]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2019.3.3  Build #IU-193.6494.35 
2020-03-16 09:38:09,514 [  81689]  ERROR - plication.impl.ApplicationImpl - JDK: 11; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2020-03-16 09:38:09,514 [  81689]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
```

**Comment by dmitry-fa** [comment]
It's very strange:
> java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V

Looks an ancient version of the com.google.common.base.Preconditions class is used.
`public static void checkArgument(boolean b, @Nullable String errorMessageTemplate, char p1)`
was introduced on 01 Feb 2016.

**Comment by asm0dey** [comment]
Which version is it? Currently I suppose it's really JetBrains runtime fall
and possibly we have several guavas in classpath.

First is root of NoClassDefFound and second may be root of NoSuchMethodError

пн, 16 мар. 2020 г. в 20:20, Dmitry <notifications@github.com>:

**Comment by dmitry-fa** [comment]
> Which version is it?

I can't say for sure, probably 19.0 or earlier.
https://mvnrepository.com/artifact/com.google.guava/guava

> First is root of NoClassDefFound and second may be root of NoSuchMethodError

I think so. `NoClassDefFoundError: Could not initialize class BaseEncoding ` is certainly caused by an exception is the static initialization code of BaseEncoding. But I haven't managed to reproduce such exception loading classes throwing exception during constant initilization. Probably BaseEncoding is loading by an alternative class loader.

**Comment by asm0dey** [comment]
So I think we should close this ticket cause it can't be reproduced. Thank
you for your help!

пн, 16 мар. 2020 г. в 22:21, Dmitry <notifications@github.com>:

**Comment by dmitry-fa** [comment]
Yes, you can close this ticket and open it again later if the problem appears again or you have more details. 
Glad to help :)

**Comment by asm0dey** [comment]
Thanks!
