### ISSUE TITLE
StorageException: 404 Not Found

### ISSUE THREAD

**Issue by swatijain1101** [googleapis/java-storage#49]
We make use of Google's JAVA client library to create storage client using which we get a particular blob by: storageClient.get(blobId).

We are facing an issue - calling the above method intermittently leads to "StorageException: 404 Not Found". Even when the objects exists and can be seen from console.

Below is the stack-trace: 
```
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT **Caused by: com.google.cloud.storage.StorageException: 404 Not Found**
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT No such object: <our object name - we would not want to disclose>
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.load(HttpStorageRpc.java:588) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:464) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[gax-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl.readAllBytes(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.Blob.getContent(Blob.java:455) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.sap.hcp.osaas.cfbroker.utils.GCPUtils.getBlob(GCPUtils.java:60) ~[classes/:?]

   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	... 89 more
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT **Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found**
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT No such object: <our object name we would not want to disclose>
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065) ~[google-http-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:380) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:6189) ~[google-api-services-storage-v1-rev114-1.23.0.jar!/:?]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.load(HttpStorageRpc.java:584) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:464) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[gax-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl.readAllBytes(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at **com.google.cloud.storage.Blob.getContent**(Blob.java:455) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
```

Can there be anything that we might be missing? or is it an issue on the library side?

Thanks,
Swati Jain

**Comment by dmitry-fa** [comment]
Hello @samir

Sorry for the long delay.

According to  [the storage consistency spec](https://cloud.google.com/storage/docs/consistency) read-after-write should never cause 404 Not Found.
After 5 day running of the program similar to you I'm not able to reproduce your 404 .
One can only guess about the reasons which lead to the 404 error. Some of them:

- someone starts the same service on the same bucket (might be nightly build test)
- someone else who has an access to your bucket may delete/move/cleanup your data
- name collision in multithreading environment:
                    `String eventsPath = element.getKey() + "/" + date.get() + "/events.csv";`
                   ` String tempPath = element.getKey() + "/" + date.get() + "/temp_events.csv";`
   Such names might be not unique,  I quite admit that another thread may perform operations on an object with the same name
- your call: `createGcsFile(bucketName, eventsPath);` does not really create a blob. It could:
   - ignore throwing exceptions
   - try create a blob in another thread
   - by mistake do not create an object

There could be many other reasons, but I'm pretty sure your application is doing something wrong.

**Comment by vali7394** [comment]
I'm facing same issue. I'm using spring batch to do validations(partitioning) then write the files to GCS. If there are validation error files then merge those files into one consolidated file in next step. I'm getting below error though file exist in the folder. "com.google.cloud.storage.StorageException: Object 6_Error_permuploadinput.csv (generation: 0) not found." Any help is really appreciative. 

request.setTarget(
            BlobInfo.newBuilder(bucketName, filePath + VALIDATION_CONSOLIDATED_ERROR_FILE_PREFIX+fileName).build());
        List<String> filesToMerge = getFileNamesToMerge(jobExecution,fileKey,fileName);
        for (String name : filesToMerge) {
            request.addSource(name);
        }
        Blob compositeObject = gcsStorage.compose(request.build());

**Comment by vali7394** [comment]
FYI. Every-time it reports different file is missing.
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Object 4_Error_permuploadinput.csv (generation: 0) not found.",
    "reason" : "notFound"
  } ],
  "message" : "Object 4_Error_permuploadinput.csv (generation: 0) not found."

<img width="691" alt="Screen Shot 2020-12-02 at 11 00 54 AM" src="https://user-images.githubusercontent.com/25043729/100897537-c9773d00-348d-11eb-9d31-348fd7421b8f.png">

**Comment by vali7394** [comment]
@dmitry-fa - We identified the root cause. This is an application issue. Apologies for inconvenience.
