### ISSUE TITLE
Storage: NPE on storage.get(bucket, "")

### ISSUE THREAD

**Issue by captainju** [googleapis/java-storage#870]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: debian
3. Java version: 11
4. storage version(s): 1.115.0

#### Steps to reproduce

  1. create a bucket
  2. get blob on the empty blob name

#### Code example

```java
Blob blob = storage.get(bucketName, "");
```

#### Stack trace
```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:892)
	at com.google.cloud.storage.BlobId.of(BlobId.java:114)
	at com.google.cloud.storage.BlobId.fromPb(BlobId.java:118)
	at com.google.cloud.storage.BlobInfo.fromPb(BlobInfo.java:1160)
	at com.google.cloud.storage.Blob.fromPb(Blob.java:958)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:330)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:311)
```

I know it's a bit weird to ask for the empty blob, but it shouldn't produce a NPE.

**Comment by BenWhitehead** [comment]
I believe this is working as intended, and is directly driven by the data received from the backend service.

I ran a similar test with http logging enabled and we can see the full request and response:
```
2021-06-14 16:21:21,456 INFO  [main] c.g.a.c.h.HttpTransport   - {     } -------------- REQUEST  --------------
GET https://storage.googleapis.com/storage/v1/b/my-testing-bucket/o/?projection=full
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gcloud-java/1.115.0 Google-API-Java-Client/1.31.5 Google-HTTP-Java-Client/1.39.2 (gzip)
x-goog-api-client: gl-java/1.8.0 gdcl/1.31.5 linux/5.10.28

2021-06-14 16:21:21,609 INFO  [main] c.g.a.c.h.HttpTransport   - {     } -------------- RESPONSE --------------
HTTP/1.1 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Length: 32
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Jun 2021 20:21:21 GMT
Expires: Mon, 14 Jun 2021 20:21:21 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin

2021-06-14 16:21:21,622 INFO  [main] c.g.a.c.h.HttpTransport   - {     } Total: 32 bytes
2021-06-14 16:21:21,623 INFO  [main] c.g.a.c.h.HttpTransport   - {     } {
  "kind": "storage#objects"
}


java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:892)
	at com.google.cloud.storage.BlobId.of(BlobId.java:114)
	at com.google.cloud.storage.BlobId.fromPb(BlobId.java:118)
	at com.google.cloud.storage.BlobInfo.fromPb(BlobInfo.java:1160)
	at com.google.cloud.storage.Blob.fromPb(Blob.java:958)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:330)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:311)
	at com.google.benwhitehead.Issue870.name(Issue870.java:29)
```

The `com.google.cloud.storage.Storage#get(java.lang.String, java.lang.String, com.google.cloud.storage.Storage.BlobGetOption...)` method is really only useful so long as the Blob it gets a handle to has a populated `name` (notice in the returned json above a single property `kind`) property which is required for all operations per https://cloud.google.com/storage/docs/json_api/v1/objects. 

If you change from a get operation to a write operation the backend will in fact return a `400 Bad Request`
```
{
  "error": {
    "code": 400,
    "message": "No object name",
    "errors": [
      {
        "message": "No object name",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
```
